set -e CRYPTO_EXCHANGE
set -e CRYPTO_API_KEY 
set -e CRYPTO_API_SECRET
set -e CRYPTO_API_PASSWORD 
set -e CRYPTO_API_UID

set -Ux CRYPTO_EXCHANGE coinbasepro
set -Ux CRYPTO_API_KEY b667c4115c78e95860610a1dabe0766a
set -Ux CRYPTO_API_SECRET Iw3LpJl4ktSTuyxJuSKrUUDoEcvqpC5ksEvNkyqBMoAM+/PA4COlgVZ80wXHGaNTdPA6lAyAE1R/vU6vtwPd0A==
set -Ux CRYPTO_API_PASSWORD vx0uzar5mn
set -Ux CRYPTO_API_UID ''
